### ISSUE TITLE
Research internal Java MIDI playback for custom soundfonts

### ISSUE THREAD

**Issue by wyskoj** [wyskoj/midis2jam2#10]
Right now I'm using CoolSoft MIDISynth for Windows but I need to figure out the best alternatives for MacOS and Linux. The internal Java MIDI synth works fine for now though.

**Comment by cunningar0807** [comment]
I was thinking the same thing.

The Mac OS csvmidi built in synth might sound terrible, and there isn't a way to change the soundfont in a .jar file.

**Comment by wyskoj** [comment]
To make it clear, MIDICSV is only a CLI utility for converting .mid to .csv. It doesn't have any relation to the playback. I'm not aware of any way to change Java's synthesizer's soundfont, but it is worth investigating. The alternative to this is to run an external synth that the Java MIDI transmitter can connect to (I have success doing this on Windows with VirtualMIDISynth).

**Comment by wyskoj** [comment]
Resolved by 1618fff
