### ISSUE TITLE
Combine the triangle percussion notes

### ISSUE THREAD

**Issue by FriendlyFloyd** [wyskoj/midis2jam2#108]
Something I wanted to resolve since the first MIDIJam, I think it would make more sense to merge the "Triangle" and "Mute Triangle" into a single model, with the hand (or other dampener) appearing to mute the triangle, and either moving away or disappearing for the open note

**Comment by lickington** [comment]
Well then, combining the triangle notes would be a big problem, because if the open and mute triangles were playing at the same time, that would mean that there would be duplications.

**Comment by FriendlyFloyd** [comment]
When would they play at the same time? Couldn't it work like the hi-hat?

**Comment by lickington** [comment]
I once listened to an MID file where both of them played at the same time, and only one of them showed up. Weird. 😕

**Comment by FriendlyFloyd** [comment]
Like I said: it works on similar logic to hi-hat. There's actually a value that you can use to stop one MIDI note from playing when another is triggered (I think it's called "delta" something?), and that's how you can get the hi-hat and triangle to stop the "open" note once the "closed" note is played.
