### ISSUE TITLE
Improve performance in multiple areas

### ISSUE THREAD

**Issue by VGMRUS** [wyskoj/midis2jam2#115]
**Describe the bug**
The enhanced shadows REALLY need some optimization, specially with high amounts of instruments showing up at once.

I have a RX580 4gb (and ryzen 3700x), and it is struggling to get to 60fps and sometimes even 30fps and with enough instruments not even 15fps with the shadows at low (doesn't change the performance much with medium and high shadows).

If I put the enhanced shadows on OFF it runs 144fps easily, so these shadows are really slowing down the performance and they should be optimized

IDK if it's because this RX580 is a AMD card and amd card windows drivers are NOTORIOUS for bad OpenGL performance compared with nvidia or even intel, if midis2jam2 is using OpenGL that could be a factor and adding vulkan support would fix it

**Offending MIDI file**
Upload the MIDI file that causes the bug here.
Any midi with more than 10-20 instruments or more showing up at once really, compare the performance on the same midi with shadows off vs shadows on low/medium/high)

**Expected behavior**
The drop of FPS shouldn't be as big just from shadows on an rx580 mid end card, this card should be more than enough to run midis2jam2 at more than 60fps all the time

**System**
Provide your OS, and computer specs if applicable.
windows 10 21H2, 2x8gb of ddr4 2666mhz, ryzen 3700x, rx 580 4gb

**Comment by wyskoj** [comment]
Open Task Manager and start a MIDI file. Does your GPU show any usage? Here's what mine looks like:
![image](https://user-images.githubusercontent.com/31376393/176301053-e86c9767-a491-4d81-b51c-1f422393f762.png)

**Comment by wyskoj** [comment]
As far as "optimization" goes, there's not much I can do. I don't manage any of the rendering and graphics component of the application. That's all on jMonkeyEngine and I just use that to create the graphics. My guess is with a graphics card that nice and you are getting shitty performance, it's just not being utilized since it's AMD.

**Comment by VGMRUS** [comment]
Not that high gpus usage actually:
the first sixth midijam wasn't open, after that it was
I've just noticed the instrument that decrease the fps the most are the pianos, 2-4 or more pianos really decrease the performance
max total cpu usage I've seen is 8%, when looking at the per thread cpu usage it uses like 2 threads at max usage in each thread at like 50%-60% usage max on each of those threads
![imagen](https://user-images.githubusercontent.com/87239717/176324335-5d5a1e0f-7890-4c05-9f70-5f8f9c54356c.png)
Cheers

**Comment by VGMRUS** [comment]
Here in this scene you can see how it only makes 20fps with shadows on low
Here's the midi if you want to compare: [Back to the Future II Round 2-1 SNES Official.zip](https://github.com/wyskoj/midis2jam2/files/9006263/Back.to.the.Future.II.Round.2-1.SNES.Official.zip) ![imagen](https://user-images.githubusercontent.com/87239717/176325696-b0918989-dd6f-47ec-8083-3bf395766890.png)

**Comment by wyskoj** [comment]
Can you also open that file again, press F3, and take a screenshot please?

**Comment by wyskoj** [comment]
I'm testing it out now and I notice I'm getting only about 30-45 fps myself, so you are right with regard to the frame drop. I will spend some time trying to find the root cause of it.

**Comment by VGMRUS** [comment]
Sure ![imagen](https://user-images.githubusercontent.com/87239717/176486762-bf1ffaca-07e3-4e7a-8ad0-166a8282f642.png)

**Comment by wyskoj** [comment]
I also just found out that the SSAOFilter (screen space ambient occlusion) was adding a lot of extra overhead! Gonna try to tweak this to improve its perfomance.

**Comment by wyskoj** [comment]
At this point I've entirely refactored the event collection system. Performance, as it relates to the computation of animation—not necessarily rendering, although that has been optimized and is configurable—has been significantly optimized.

**Comment by wyskoj** [comment]
> Here in this scene you can see how it only makes 20fps with shadows on low

This MIDI file runs at a smooth 60 FPS now!
