### ISSUE TITLE
Support for Drag and Drop midi files into Midis2Jam2 Launcher

### ISSUE THREAD

**Issue by VGMRUS** [wyskoj/midis2jam2#119]
**Is your feature request related to a problem? Please describe.**
This feature was actually working before on older versions (1.3 of example) of midis2jam2 with the old launcher (you would drop the file into the midi file window) and not having it anymore is a bit of a bummer, since IMO this is one of the fastest ways to change the midi into the one you want

**Describe the solution you'd like**
Simple, you drag a midi file from the windows explorer into anywhere midis2jam2 launcher and the midi to play changes to that one

**Comment by wyskoj** [comment]
Only possible thanks to [this tweet](https://twitter.com/tkuenneth/status/1331993022955917312/photo/1).
