### ISSUE TITLE
Can't Change Window Resolution Manually (midijam2 visualizer window) Anymore

### ISSUE THREAD

**Issue by VGMRUS** [wyskoj/midis2jam2#128]
**Describe the bug**
In the prior version (1.5) you could manually resize the window by dragging the borders and also you had a maximize button on the window that it's not there anymore, this is bothering me because I use a external program to resize the window to the two very specific window resolutions (one horizontal 1841x1064 and a vertical 1040x1880 one) called Sizer to record midis2jam2 with a OBS overlay and while it does force it to that resolution, there's a problem, the image streches, so this unability to change the window size manually needs to be added back for it to not strech like that

**Expected behavior**
The manual adjust window size on the borders on the window and also to add the missing maximize window

**Screenshots**
Here you can see what happens if you make the default horizontal window size into a vertical 1040x1880 resolution:
![imagen](https://user-images.githubusercontent.com/87239717/181049918-1379a198-3e38-4259-95a1-3a97e2fe0097.png)

**Comment by wyskoj** [comment]
A limitation of using the [`FilterPostProcessor`](https://wiki.jmonkeyengine.org/docs/3.4/sdk/filters.html) to add shadows, ambient occlusion, bloom, etc. is that the resolution becomes fixed. The ability to resize and maximize the window has been removed because of this.

**Comment by VGMRUS** [comment]
So the only way to "fix" this then would be to have a option to disable those effects I guess, welp we tried
