### ISSUE TITLE
Small Problem Capturing midis2jam2 with OBS since version 1.5

### ISSUE THREAD

**Issue by VGMRUS** [wyskoj/midis2jam2#130]
**Describe the bug**
There's a small (but annoying) problem with capturing midis2jam2 visualizer windows starting the 1.5 version, I don't know what could have caused this but,

Since the version 1.5 OBS will keep capturing the visualizer window even when it's closed and if you try to open/play another midi it won't capture the new visualizer window at all and keep capturing the first already closed frozen window, it's really annoying and to fix this you have to either mess with which window OBS is capturing or close midis2jam2 completely

when you close the launcher the closed visualizer window that is still being captured (even though it's closed) stops being captured by OBS

In the version 1.4 when the visualizer windows closes OBS also stops capturing said window immediately which was really good behaviour

It's like since 1.5 the visualizer window didn't close completely and OBS was detecting that making this issue, so if there's any remain of this window when getting closed getting rid of it should probably fix it

**Expected behavior**
When the visualizer window gets closed OBS should detect that the captured window is gone and stop the capture (like in version 1.4)

**Screenshots**
OBS basically keeps the last frame shown on the visualizer window as if it were a image instead of stoping capture as it should (as it does in version 1.4)
![imagen](https://user-images.githubusercontent.com/87239717/181060855-f820c6cf-d5d5-47d2-b424-8d395ce70bca.png)

**Comment by wyskoj** [comment]
Enable the legacy display engine.

In v1.7, the legacy display engine will become the default (4843e27232a8ac358351f83bd61ba33db0580136), so this issue will be fixed.

**Comment by VGMRUS** [comment]
Legacy display being enabled does fix it, thanks
