### ISSUE TITLE
LWJGLv2 causes startup issues on some systems

### ISSUE THREAD

**Issue by VGMRUS** [wyskoj/midis2jam2#132]
**Describe the bug**

Since [this build](https://ci.appveyor.com/project/wyskoj/midis2jam2/builds/44130484) the visualizer window simply won't show up when you press start, start becomes gray and nothing else happens, at least in the [latest build](https://ci.appveyor.com/project/wyskoj/midis2jam2/builds/44299399) it does show an error as you can see below

**Offending MIDI file**

It happens with any midi

**Screenshots**
Here is the error that shows on the [lastest build](https://ci.appveyor.com/project/wyskoj/midis2jam2/builds/44299399)
![imagen](https://user-images.githubusercontent.com/87239717/182020570-4175bcce-0539-4837-8631-045475bf763e.png)

**System**
Provide your OS, and computer specs if applicable.
Windows 10 21H2, ryzen 7 3700x, 16gb ram, rx 580 4gb

**Comment by wyskoj** [comment]
Please do not open issues on commits that are not on the main branch.

**Comment by wyskoj** [comment]
@VGMRUS Does your issue still persist on the [latest build](https://ci.appveyor.com/project/wyskoj/midis2jam2/builds/44465003/artifacts)?

**Comment by VGMRUS** [comment]
Yes, even in the latests version, as you can see on this gif it just does nothing, the visualizer window won't show up:
![Midi2jam2 bug](https://user-images.githubusercontent.com/87239717/184676571-e78ae36c-c8f3-4f25-ae00-327339304c23.gif)

**Comment by wyskoj** [comment]
Do any errors appear in the console output?

**Comment by VGMRUS** [comment]
I'm not getting any errors like last time, no, I've tried F3 but it doesn't do anything without the visualizer window

**Comment by wyskoj** [comment]
Can you take a screenshot of the console window after you've pressed start?

**Comment by VGMRUS** [comment]
I meant that the error window didn't show up like last time, how do I open the console?

**Comment by wyskoj** [comment]
Can you try running the .jar file in another location on your computer? Preferably somewhere on the C: drive, perhaps your desktop.

**Comment by VGMRUS** [comment]
ok 
![imagen](https://user-images.githubusercontent.com/87239717/184709226-96ea00d4-e7e6-426f-9689-02d5df54f084.png)

**Comment by wyskoj** [comment]
Looks like you are running it with Java 16, can you try using Java 11 instead? I have some [instructions written](https://midis2jam2.xyz/running-experimental-builds) if you need it.

**Comment by manu-romero-411** [comment]
Hello, I'm also trying to run the program without luck.
I'm using Java 11 (from Oracle JDK 11) on Windows 10 21H2
This is the console output when only selecting the `.mid` file:

![image](https://user-images.githubusercontent.com/14951907/184712093-64d2b2b8-4707-404b-bf5c-595ba275b3a6.png)

However, when clicking Start, nothing happens on the main window.
On the console, this appears:

![image](https://user-images.githubusercontent.com/14951907/184712573-7f65bf94-6ab3-432e-a50e-8bdbf8ceaf5f.png)
![image](https://user-images.githubusercontent.com/14951907/184712606-91bd1358-4800-48ab-8b7d-6aba0aacf3d8.png)

**Comment by VGMRUS** [comment]
Here with version 11 ![imagen](https://user-images.githubusercontent.com/87239717/184716003-b9dcc561-4bc2-44cb-98b8-05e5a971479b.png)

**Comment by wyskoj** [comment]
@manu-romero-411 @VGMRUS can you both try using [this build](https://ci.appveyor.com/project/wyskoj/midis2jam2/builds/44245181/artifacts) and post your result?

**Comment by wyskoj** [comment]
And just to confirm, you both are on a 64-bit machine, correct?

**Comment by manu-romero-411** [comment]
Unfortunately, the program doesn't work with your latest build.

![image](https://user-images.githubusercontent.com/14951907/184720383-c48e264d-e962-487a-a78e-710f9af57165.png)

I'm on a 64-bit machine, correct :)

**Comment by wyskoj** [comment]
> Unfortunately, the program doesn't work with your latest build.

I understand that. I need you to try the other build I mentioned above:
> can you both try using [this build](https://ci.appveyor.com/project/wyskoj/midis2jam2/builds/44245181/artifacts) and post your result?

**Comment by VGMRUS** [comment]
yes 64 bit, that build you posted does work normally (visualizer window opens) but it has these warnings:
![imagen](https://user-images.githubusercontent.com/87239717/184721415-acc5274e-72f8-41ba-ba2e-a13f2f1d8b13.png)
![imagen](https://user-images.githubusercontent.com/87239717/184721484-1c01b9d0-d8cd-4907-a00d-0c04f362cbe5.png)
![imagen](https://user-images.githubusercontent.com/87239717/184721543-aaa84e59-a4ff-4701-92e7-6979f65bf5f4.png)

**Comment by manu-romero-411** [comment]
> > Unfortunately, the program doesn't work with your latest build.
> 
> I understand that. I need you to try the other build I mentioned above:
> 
> > can you both try using [this build](https://ci.appveyor.com/project/wyskoj/midis2jam2/builds/44245181/artifacts) and post your result?

Oops, sorry, I got into trouble auto-completing the commit hash at the end of the file names.

And yes, this is working:

![image](https://user-images.githubusercontent.com/14951907/184721970-040c311d-5cd5-4094-a349-15ac52639cdd.png)

**Comment by wyskoj** [comment]
The warnings can safely be ignored. 

Glad to see it working! I think this narrows down the problem to a LWJGL versioning issue. I'll make sure this is resolved in the next update.

**Comment by VGMRUS** [comment]
Hi, I can confirm that the [last build](https://ci.appveyor.com/project/wyskoj/midis2jam2/builds/44501538/artifacts) works without any issue, the visualizer window starts as it should. Cheers

**Comment by wyskoj** [comment]
This issue is resolved, further work needs to be done on #125.
