### ISSUE TITLE
对于midis2jam2的一些意见和问题。

### ISSUE THREAD

**Issue by wodr4** [wyskoj/midis2jam2#139]
**Is your feature request related to a problem? Please describe.**
这些是意见和问题。

**Describe the solution you'd like**
1.拨片贝斯可以把拨片器显示出来吗？
2.你们能用什么方法把finger bass和slap bass区分出来吗？
3.希望midis2jam2能够早点把所有乐器都可视化。下面我会发一张图，图中绿色表示已实现（只有drums的音色），橙色表示还需要再改进一下的，红色表示未实现的。

**Describe alternatives you've considered**
图片：
![无标题](https://user-images.githubusercontent.com/111207456/184518636-0db3c726-726f-4117-9ddb-f03ff36944b4.png)
希望红色的可以早点可视化，橙色的可以早点改进。

**Additional context**
无。

**Comment by wyskoj** [comment]
1. "Picked bass" currently does not look any different than the other basses. I will experiment with adding a guitar pick to the animation.
2. Currently, no.
3. Thanks for the picture. I also have a [document ](https://github.com/wyskoj/midis2jam2/blob/master/implementation.adoc)listing each instrument and its status.

Thanks for your interest in midis2jam2, I will eventually get to adding the rest of the instruments.

**Comment by wodr4** [comment]
我发现不同的midi音源中，“Drums”的音色是不同的，你文件中的打击乐器音色表只适用于Microsoft MIDI 映射表和Microsoft GS波表软件合成器这两种音源，其它音源不能完全适用。我个人比较喜欢Yamaha S-YXG50 VSTi音源，嘿嘿。。

**Comment by mckuhei** [comment]
> 2.你们能用什么方法把finger bass和slap bass区分出来吗？

I think we can use English.

**Comment by mckuhei** [comment]
> 我发现不同的midi音源中，“Drums”的音色是不同的，你文件中的打击乐器音色表只适用于Microsoft MIDI 映射表和Microsoft GS波表软件合成器这两种音源，其它音源不能完全适用。我个人比较喜欢Yamaha S-YXG50 VSTi音源，嘿嘿。。

[This program is GM compatible.](https://midis2jam2.xyz/#:~:text=Complete%20GM%20implementation.) If you want XG support, You can fork and modify you self. I think author is not planned to support XG.

**Comment by wyskoj** [comment]
Closing this comment as it only relates to the implementation of instruments.
