### ISSUE TITLE
Harp Strings should ring out/sustain after they've been played

### ISSUE THREAD

**Issue by cunningar0807** [wyskoj/midis2jam2#14]
As I was mentioning a while back, I think it would be appreciated if the harp strings in midijam should sustain/ring out, like what you would normally see on a real harp. The tubular Bells/Chimes in the program actually do that automatically, so why not the harp strings too?

**Comment by wyskoj** [comment]
I am implementing animations are they are seen in MIDIJam, so if MIDIJam doesn't do that, then it's likely I won't implement it.
