### ISSUE TITLE
Some Midi Files won't work when opening the Midis2Jam2 Jar File

### ISSUE THREAD

**Issue by cunningar0807** [wyskoj/midis2jam2#15]
So I was trying to test out onestop.mid with the midis2jam2 jar file, but for some reason, I get an error message.

![Midi File Error](https://user-images.githubusercontent.com/32210900/113489194-c7030f00-9490-11eb-8392-9f45fe61ed68.png)

I tried out some other midi files that you can check out [here](https://we.tl/t-ZEtSUunzsB) and they literally do the same thing and give me the same error message.

Maybe it's because these midi files are too powerful, or that they're offbeat or syncopated way too much? Or maybe they were created with a professional midi editing program.

Is there a way you could fix this problem?

**Comment by wyskoj** [comment]
It seemed to be an issue with MIDICSV and Windows-1252 encoding. All fixed.
