### ISSUE TITLE
Autocam focusing on Trombone clips through Stringed instrument

### ISSUE THREAD

**Issue by Alto1772** [wyskoj/midis2jam2#154]
Title says it all, with camera coordinates zoomed in from below screenshot:
![midis2jam2_TG4s3GujhP-1](https://user-images.githubusercontent.com/56553686/209357308-bf7ab8d6-9881-4e21-b430-3b43b1289b7e.png)

full screenshot:
![image](https://user-images.githubusercontent.com/56553686/209356697-a91c260a-c2ad-4ec3-b8e3-246d3b794182.png)

**Comment by wyskoj** [comment]
I've had plans to move the Trombone entirely, so when I do that this will be resolved.

**Comment by s11141827** [comment]
I'm excited for the next update
