### ISSUE TITLE
Japanese characters do not render correctly

### ISSUE THREAD

**Issue by src3453** [wyskoj/midis2jam2#158]
**Describe the bug**
Multibyte characters (maybe) in dialog in Japanese environment are garbled.

**Offending MIDI file**
-none-

**Expected behavior**
When displaying multibyte characters (maybe) in a Japanese environment

**Screenshots**
![bug](https://user-images.githubusercontent.com/103661526/210032359-0c66b3c7-06d0-4060-9b65-60cb0010e375.png)

**System**
Windows 10 Home 22H2 Build 19045.2364 CPU: Ryzen 5 2400G

**Additional context**

**Comment by wyskoj** [comment]
@src3453 This issue should be resolved with v1.8.0. If not, let me know!
