### ISSUE TITLE
After 1 use, soundfont no longer works

### ISSUE THREAD

**Issue by BezierCurves** [wyskoj/midis2jam2#161]
**Describe the bug**
After a soundfont is used once, the soundfont cannot be used again. Instead, an error message pops up if you press "Start" with the offending soundfont.

**Offending MIDI file**
It seems that all MIDI files are affected.

**Expected behavior**
The MIDI file plays as usual with the selected sound

**Screenshots**
<img width="1440" alt="Screen Shot 2023-03-10 at 3 44 36 PM" src="https://user-images.githubusercontent.com/127568765/224451425-86ccef8b-7b88-4aed-b4bd-87a97dbcb7e0.png">

**System**
Provide your OS, and computer specs if applicable.
macOS version 12.3.1, MacBook Air
**Additional context**
It seems that all soundfonts are affected.

**Comment by wyskoj** [comment]
@BezierCurves Let me know this issue persists with v.1.8.0.
