### ISSUE TITLE
Gervill mixer

### ISSUE THREAD

**Issue by wyskoj** [wyskoj/midis2jam2#166]
Some users have interested in having a mixer to solo, mute, and adjust the volumes of channels. This should be possible, but only when the selected device is Gervill. In theory, midis2jam2 could manipulate an external device, but that device should have its own mixer—so having one in midis2jam2 would be redundant.

![image](https://github.com/wyskoj/midis2jam2/assets/31376393/6035b6fe-b74a-4748-8c90-94645260ec53)

The Gervill mixer could look similar to the VirtualMIDISynth mixer, as seen above.

**Comment by s11141827** [comment]
Neat idea

**Comment by s11141827** [comment]
I love mixers.

**Comment by wyskoj** [comment]
I'm going to close this issue for the following reason: Gervill does not natively support changing the volume of channels in a way that is immutable to changes from MIDI events. And the primary focus of midis2jam2 is the animation, not necessarily MIDI synthesis. This is why midis2jam2 is easy to connect to a separate synthesizer for more granular control. So because it is not trivial to implement (will require a significant overhaul of the synthesizer), I'm not interested in implementing it (if the community wants to contribute development of this feature, I would have no objection).
