### ISSUE TITLE
Be able to configure what midi track + program goes to what instrument

### ISSUE THREAD

**Issue by orangeisbetter** [wyskoj/midis2jam2#169]
**Is your feature request related to a problem? Please describe.**
Sort of. I'm trying to make a midi file that's to be rendered with midis2jam2, and the lasers (the ones that map to the lead 1 and lead 2) sometimes change to the sawtooth or square keyboard if the midi file is made a specific way, and it seems kind of random.

**Describe the solution you'd like**
I'd like a settings panel that allows you to match a midi program on a specific track to map to a certain instrument. For example, you could select track 2, and say that any midi events that map to program 81, for example, are going to be played by the lasers instead of the keyboard.
This would also allow certain sounds to be played by different instruments. For example, if you have an ocarina sound that sounds the best for your application, but you want the instrument to be a flute, you can change that.

**Describe alternatives you've considered**
Changing around the instruments in the MIDI file, and then finding some quirky solution, and hoping that by chance it does what I want it to do

**Additional context**
I feel like more customization that helps to correlate the midi file to the animation would make the user experience so much better.

**Comment by s11141827** [comment]
That would totally rock

**Comment by wyskoj** [comment]
@orangeisbetter The logic behind picking between lasers and keyboards is polyphony ([seen here](https://github.com/wyskoj/midis2jam2/blob/e93981b4862fe8f4e1a8d2178814ed9e7161b37e/src/main/kotlin/org/wysko/midis2jam2/instrument/algorithmic/InstrumentAssignment.kt#L282)). This issue has been talked about in the past (#146) and I think for now I am going to stick with my previous decision.
