### ISSUE TITLE
MidiJam auto close after I open the program

### ISSUE THREAD

**Issue by zoccorus** [wyskoj/midis2jam2#171]
Please fix the program is auto closed

https://github.com/wyskoj/midis2jam2/assets/69337817/1ef27a23-e499-45eb-994b-1e32b6567008

**Comment by wyskoj** [comment]
I'll be releasing a new version soon. When that version is released, let me know if the issue persists.e

**Comment by wyskoj** [comment]
@zoccorus Closing until further information is provided.
