### ISSUE TITLE
Setting a background color prevents you from opening the background settings again

### ISSUE THREAD

**Issue by ArieTheTrainGirl** [wyskoj/midis2jam2#174]
**Describe the bug**
I set a background color in the Background settings (a hot pink), and now every time I attempt to re-enter the Background settings throws me an error relating to an HSV value being out of range.

**Offending MIDI file**
No MIDI file used.

**Expected behavior**
I expected to be able to change the background color and use it (and, using the color does work in playback), and be able to re-enter the background settings to change it. 

**Screenshots**
![image](https://github.com/wyskoj/midis2jam2/assets/76417791/848de6f0-852d-4c35-94cb-ff7fd64f16f0)

**System**
Windows 10 Pro
Ryzen 7 3700X
AMD Radeon RX 6700XT
32GB DDR4

**Additional context**
I tried reinstalling and clearing the folders in Program Files, yet it keeps the background color set. Can't figure out where it's storing the data in registry to delete it and get a fresh install, so I simply just can't enter the background settings ever again (I guess).

Would like to know how I can completely reset everything because uninstalling & reinstalling did not resolve this. Is there a directory that the program saves to that I can delete to get fresh settings?

**Comment by wyskoj** [comment]
Sorry this is affecting you. You can clear all configuration options by deleting the `.midis2jam2` folder in your user folder (you may need to enable hidden files and folders to see it).

**Comment by ArieTheTrainGirl** [comment]
Thank you for the quick reply! This helped and I was able to get back in. 

Hope the information I've given helps for patching any bugs that might exist with this!
