### ISSUE TITLE
Can't select actual MIDI devices in Linux

### ISSUE THREAD

**Issue by steviator** [wyskoj/midis2jam2#178]
**Describe the bug**

None of my various MIDI devices show up in Midis2jam2 in Linux, making it useless.

**Offending MIDI file**
Upload the MIDI file that causes the bug here.

All midi files sound like shit.

**Expected behavior**

Working like in Windows and Mac, where native MIDI devices can be used.

**Screenshots**

Not required. Picture a list of MIDI devices containing only the built-in Anal Gerbil ear torture device or whatever it's called.

**System**
Provide your OS, and computer specs if applicable.

Arch

**Additional context**

**Comment by wyskoj** [comment]
Closing until further information provided.
