### ISSUE TITLE
Intel Graphics HD 3000 causing crash on startup

### ISSUE THREAD

**Issue by MijunElMacho21** [wyskoj/midis2jam2#179]
There Is A Java Error In Your App!

Graphics Driver Name: Intel Graphics HD 3000

![Screenshot_3](https://github.com/wyskoj/midis2jam2/assets/132280765/0ff25dd2-591e-4575-984f-f2243ecff0bd)

The First Error Says:

"WGL: The driver does not appear to support OpenGL
Exception: WGL: The driver does not appear to support OpenGL"

The Second Error Says:

"Failed to create display
RuntimeException: Failed to create the GLFW window"

Tell Me How To Fix It! Please!

Regards
- Raphael Mammadoffe

**Comment by wyskoj** [comment]
[Try these instructions](https://gist.github.com/rb-dahlb/26f316c5b6089807a139fc44ee69f0d1) and see if it remedies your issue.

**Comment by wyskoj** [comment]
Closing this issue until further notice is provided.
