### ISSUE TITLE
RealTimeSequencer drifts out of sync when tempo events occur

### ISSUE THREAD

**Issue by peppinodoesmidi** [wyskoj/midis2jam2#181]
so while i was making deathdeservioli midi from pizza tower i tested it with midis2jam2 but when the bpm slide started it was going so slow and the instruments weren’t playing in the right place or time so i hope you can fix this

**Comment by wyskoj** [comment]
@peppinodoesmidi Please provide a MIDI file that causes the issue you describe. (You will need to ZIP it before uploading because GitHub does not allow MIDI files to be uploaded.)

**Comment by saverofthewos** [comment]
This happens with any midi with a BPM slide, for example 
[[Black MIDI] RUSH E (Fully RECREATED).zip](https://github.com/wyskoj/midis2jam2/files/13852005/Black.MIDI.RUSH.E.Fully.RECREATED.zip)
plays too fast.

**Comment by peppinodoesmidi** [comment]
oh ok i'll try to do taht

**Comment by peppinodoesmidi** [comment]
what i meant was there was a bpm slide glitch
[deservioli.mid.zip](https://github.com/wyskoj/midis2jam2/files/13902633/deservioli.mid.zip)
idk if you can download the zip or not but i hope this works

**Comment by wyskoj** [comment]
I've boiled this down to a bug in the OpenJDK [`RealTimeSequencer`](https://github.com/frohoff/jdk8u-jdk/blob/master/src/share/classes/com/sun/media/sound/RealTimeSequencer.java) implementation of `Sequencer`. Although it's an upstream issue, I'm going to attempt to fork it and implement my own fix.

**Comment by wyskoj** [comment]
> This happens with any midi with a BPM slide, for example [[Black MIDI] RUSH E (Fully RECREATED).zip](https://github.com/wyskoj/midis2jam2/files/13852005/Black.MIDI.RUSH.E.Fully.RECREATED.zip) plays too fast.

@saverofthewos That MIDI file doesn't have any tempo changes.

**Comment by wyskoj** [comment]
@saverofthewos Here's a CSV readout of that MIDI file. 

[[Black MIDI] RUSH E (Fully RECREATED).csv](https://github.com/wyskoj/midis2jam2/files/13943176/Black.MIDI.RUSH.E.Fully.RECREATED.csv)

If you filter the event column to only show tempo events, you can see that there is only one event.

![image](https://github.com/wyskoj/midis2jam2/assets/31376393/2bc123cd-6551-4f73-9f7b-853e8b28f821)

**Comment by saverofthewos** [comment]
That's weird. The website I downloaded it from had a tempo slide.

**Comment by peppinodoesmidi** [comment]
well for synthesia the tempo slide works and other midi software i'll see if it works

**Comment by peppinodoesmidi** [comment]
oh ok

**Comment by wyskoj** [comment]
This required a complete overhaul of the existing sequencer. Fix will be published in the next version.

**Comment by peppinodoesmidi** [comment]
k
