### ISSUE TITLE
Lyrics Duplication Display Issues

### ISSUE THREAD

**Issue by vgthecoder** [wyskoj/midis2jam2#185]
The bug occurs when there are multiple instances of the same lyric, after each other, in the MIDI file.

MIDI File: https://www.olgris.kiev.ua/des/media/M_TkOnMe.zip

I would expect the lyrics to not show duplicates of words.

In the Tom's Midi Player, under Text, it shows:
![image](https://github.com/wyskoj/midis2jam2/assets/167907693/32a1a876-2e45-4c02-9282-e0a375e3bc16)
In Midis2Jam2 it shows: 
![image](https://github.com/wyskoj/midis2jam2/assets/167907693/49d72939-5c5e-4d67-9020-88f0fd5a2c3d)

OS: Windows 10

**Comment by wyskoj** [comment]
Resolved by 4535af5b180439d29ef0b80789f285832eb6b8b4, will be fixed in v1.9.0.
