### ISSUE TITLE
Accordion/Bandoneon and French Horn overlap when played together

### ISSUE THREAD

**Issue by frog8412** [wyskoj/midis2jam2#187]
**Describe the bug**
Accordion/Bandoneon are very close to French Horn which makes them overlap

**Offending MIDI file**
Pretty much every MIDI that has them playing together, but I'll link [2 MIDIs](https://github.com/user-attachments/files/15985029/MIDIs.zip)

**Expected behavior**
Accordion+Bandoneon/French Horn should be in different positions, or alternate their positions if both instruments are displayed

**Screenshots**
![изображение](https://github.com/wyskoj/midis2jam2/assets/160930327/c11f49dc-1d6b-4288-88be-27ea5d37e1bb)

**System**
OS: Windows 10 1909 x64
CPU: AMD A6-9225 RADEON R4, 5 COMPUTE CORES 2C+3G     2.60 GHz
RAM: 4 GB

**Comment by wyskoj** [comment]
This should be an easy fix. I'll get on it!
