### ISSUE TITLE
Option to render video with no lag using ffmpeg

### ISSUE THREAD

**Issue by frog8412** [wyskoj/midis2jam2#188]
If you have ever used Ultralight MIDI Player made by PipiraMine, there's an option to render midi as video with audio and no lag. This works with ffmpeg, and so i want to see this kind of feature in midis2jam2, since some devices are struggling when playing in real time.

**Comment by wyskoj** [comment]
This has been on my backlog for quite some time, and I need to get around and implement this. Duplicate of #100. Thanks for your feedback!
