### ISSUE TITLE
Changing soundfonts using OmniMIDI's configuration window while playing a midi makes midis2jam2 freak out

### ISSUE THREAD

**Issue by frog8412** [wyskoj/midis2jam2#189]
**Expected behavior**
The app could stop making sounds and wait till OmniMIDI loads in the soundfont, just like Domino MIDI Editor does

**Additional context**
The camera moves out of bounds when not responding, however when loading a small soundfont (like SM64 soundfont) it stops doing that when it fully loads in

**Comment by wyskoj** [comment]
@frog8412 Can you record a video of your issue? I'm not sure exactly what issue you're experiencing and I'm not able to replicate that (when I change SoundFonts, it just goes silent until it is loaded—which is what I would expect).

**Comment by wyskoj** [comment]
Closing until further information is supplied.

**Comment by frog8412** [comment]
now i cant replicate it too, i think it was a performance issue lmao
