### ISSUE TITLE
Add visualized fingerings/hand positions for the missing oboe, english horn, clarinet, and bassoon presets

### ISSUE THREAD

**Issue by cunningar0807** [wyskoj/midis2jam2#19]
It might take a while before the missing instruments are added to the program, but I would like to suggest this.

I think it would be appreciated if the oboe, english horn, clarinet, and bassoon could have a visualized fingering hand position, just like the flute for example:
![Screen Shot 2021-04-05 at 11 58 35 AM](https://user-images.githubusercontent.com/32210900/113595837-8974c200-9607-11eb-8107-dd28e73ca1d0.png)

The recorder and piccolo do the same thing, but I didn't bother putting these images there anyway. Since the flute, piccolo, and recorder show fingerings and hand positions, why not do the same thing for the oboe, english horn, clarinet, and bassoon.

**Comment by wyskoj** [comment]
I'll shoot for English Horn and Bassoon in v1.6.0.

**Comment by wyskoj** [comment]
Gonna push this back a bit further.

**Comment by wyskoj** [comment]
Closing since it relates to the implementation of instruments.
