### ISSUE TITLE
Hands on some bagpipe midis dont move

### ISSUE THREAD

**Issue by pigeondriver45** [wyskoj/midis2jam2#193]
**Describe the bug**
Hands on some bagpipe midis dont move

**Offending MIDI file**
Upload the MIDI file that causes the bug here.
https://www.mediafire.com/file/bgfbkepj92eh56t/bluebonnetsovertheborder.mid/file
https://www.mediafire.com/file/7yfxndu5qdqxfrh/amazinggrace.mid/file

**Video**
https://github.com/user-attachments/assets/cbaff3e4-2ca5-424b-9a82-41c96d4feef9

**System**
Windows 11, v1.9.0 of the app

**Comment by wyskoj** [comment]
`bluebonnetsovertheborder.mid` has three tracks: bassoon, bagpipe, and shanai. The drone is played by the bagpipe, and the melody is played by the other two. midis2jam2 doesn't yet support animation for the bassoon or shanai, so they aren't seen. The hands on the bagpipe aren't moving as it's playing the drone.
