### ISSUE TITLE
it would be funny as hell if there was an option that recreated the weird behaviour from the original midijam where trying to pause the song would cause... very weird things to happen.

### ISSUE THREAD

**Issue by Rowan-Bird** [wyskoj/midis2jam2#198]
**Is your feature request related to a problem? Please describe.**
mainly just something I thought was funny. 
the original midijam had a weird thing where trying to pause using space would cause some interesting things to happen to some instruments, for example, very long spinning saxophones would appear and some instruments would appear more than once. the more you hit space, the weirder it got. I can't tell if this is a bug or a joke, but regardless it's really funny.

**Describe the solution you'd like**
Implement something reminiscent of what's shown below.

**Describe alternatives you've considered**
I don't think this exists in any form yet.

**Additional context**
![image](https://github.com/user-attachments/assets/0bb973c2-595f-4279-b302-c8b46c3f9a18)

**Comment by wyskoj** [comment]
Thanks for the issue, but I'm not interested in implementing this. While yes, it's funny, I can't see it being a popular or widely-wanted feature.

**Comment by Rowan-Bird** [comment]
that's fair. thank you for the reply.

**Comment by wyskoj** [comment]
But thank you for the issue—always open to suggestions for new features!
