### ISSUE TITLE
MIDI Device Already Used Error

### ISSUE THREAD

**Issue by SonyMvie** [wyskoj/midis2jam2#199]
When The MIDI Device Is Already Used, The Error Message Appears

**Screenshots**
![Captura de tela 2024-08-07 200835](https://github.com/user-attachments/assets/4b19ac1f-8aaa-4e3a-8d68-0bbc483606d9)

**System**
Windows 10

**Comment by wyskoj** [comment]
What MIDI device are you using that causes this error?

**Comment by SonyMvie** [comment]
Microsoft GS Wavetable Synth

**Comment by wyskoj** [comment]
Two questions:

- Does the error persist if you restart midis2jam2?
- Are you using any other software that may be using that device?

Trying to pin down what's causing this issue.

**Comment by SonyMvie** [comment]
I Wasn't Any Other Software That May Be Using That Device.

**Comment by wyskoj** [comment]
Okay, and does the issue persist even after restarting?

**Comment by SonyMvie** [comment]
Well, I Just Restarted The App.

**Comment by wyskoj** [comment]
Does the issue occur immediately after restarting the app, or after one playback? That is, do you have to start a playback once for the issue to occur, or can it occur on the first playback after opening the app?

Hope that makes sense.

**Comment by SonyMvie** [comment]
The Issue Doesn't Occur When I Restart.
