### ISSUE TITLE
Soundbank configuration does not persist 

### ISSUE THREAD

**Issue by Cartrigger** [wyskoj/midis2jam2#200]
**Describe the bug**
Currently, I have a bunch of old soundfonts that I would like to get rid of, but every single time I restart the application, it returns to what it was when I first set it over a year ago.

**Offending MIDI file**
N/A

**Expected behavior**
To save changes and not bring back old soundfonts deleted from the list.

**Screenshots**
![1](https://github.com/user-attachments/assets/68b8df99-175e-45fb-963f-84fd993ff639) 
![2](https://github.com/user-attachments/assets/cf717c44-d895-42e3-ae3a-68c32b4c8c90)
![after restart of app](https://github.com/user-attachments/assets/9017ae44-eb5d-4933-8573-1884519c5c84)

**System**
Windows 11 23H2

**Additional context**
N/A

**Comment by wyskoj** [comment]
Seems similar to #184. 

@Cartrigger Can you uninstall and then reinstall midis2jam2 and see if your problem persists?

**Comment by Cartrigger** [comment]
it persisted over a reinstall

**Comment by Cartrigger** [comment]
![image](https://github.com/user-attachments/assets/294fb984-22d1-4dcb-a295-6afeb4fd5265)

**Comment by wyskoj** [comment]
You can manually edit the `soundbanks.json` configuration file located within the `.midis2jam2` folder in your user folder (you may need to enable "Show hidden files and folders" for it to appear) as a temporary fix while I try to investigate further.

**Comment by Cartrigger** [comment]
looks good, i can do that there until a fix is made, thanks.

**Comment by Cartrigger** [comment]
UPDATE: I tried removing it, and it still exists, and reappears with my old stuff after I delete the file

**Comment by wyskoj** [comment]
Unable to reproduce at this time. @Cartrigger If this issue persists after the next release is published, please comment on this issue and I will reopen it. Thanks!

**Comment by Cartrigger** [comment]
Fixed it, had to completely remove the directory.
