### ISSUE TITLE
Some instruments still have shadows even with shadow quality set to none

### ISSUE THREAD

**Issue by raknaar** [wyskoj/midis2jam2#212]
Lowest shadow setting "none" still has shadows for parts of some instruments.
![shadows_disabled_screenshot](https://github.com/user-attachments/assets/a44339a6-d6d8-4da9-8e65-6b85630fc27b)
Tested with many midis. Drums, Keyboards, and guitars mainly affected.

**Comment by wyskoj** [comment]
The word "shadows" in this context refers to _rendered_ shadows. When set to _None_, fake shadows are displayed, which are simply raster graphics displayed on the stage floor. Any setting above _None_ will enable rendered shadows.

More information about shadow rendering can be found [on the documentation site](https://docs.midis2jam2.xyz/features/graphics/#shadow-quality).
