### ISSUE TITLE
Marimba stick disappears during pitchbend event.

### ISSUE THREAD

**Issue by vgthecoder** [wyskoj/midis2jam2#215]
Marimba stick disappears during pitchbend event.

[CARLISLE.Heaven is a place on earth K.zip](https://github.com/user-attachments/files/16956715/CARLISLE.Heaven.is.a.place.on.earth.K.zip)

The stick should move be between the two notes, and then disappear.

**Comment by wyskoj** [comment]
Mallets don't and will not support pitch bend events, as they are inherently monotonic.
