### ISSUE TITLE
AutoCam goes to bagpipes,then freezes

### ISSUE THREAD

**Issue by pigeondriver45** [wyskoj/midis2jam2#217]
**Describe the bug**
The autocam just goes to the pipes and then it doesnt show any other isntrument after that 

**Offending MIDI file**
Upload the MIDI file that causes the bug here.
Generally every midi with a Bagpipe+(another instrument)

**Expected behavior**
It would pan over to the other instruments.

**Videos**
https://github.com/user-attachments/assets/8660f053-4b13-4073-969a-b6336008652c

**Comment by pigeondriver45** [comment]
It doesnt pan to the drums actually

**Comment by wyskoj** [comment]
Will be resolved in #210.
