### ISSUE TITLE
v1.9.0 not running on Silicon Mac and Intel Mac

### ISSUE THREAD

**Issue by bijlevel** [wyskoj/midis2jam2#218]
I downloaded the app for both Arm64 and X64 and canceled the blocking. I did start the app and it seems to be running, but the home window does not appear on both systems: Mac Studio (Silicon, Mac OS Sonoma 14.7) and iMac (Intel, MacOS Monterey 12.7.6). Am I missing something?

**Comment by wyskoj** [comment]
This is a known issue. Working on a fix!

**Comment by wyskoj** [comment]
Watch #203 for updates.

**Comment by bijlevel** [comment]
OK, thank you!
