### ISSUE TITLE
Load time interrupts A/V sync

### ISSUE THREAD

**Issue by cunningar0807** [wyskoj/midis2jam2#23]
So recently I've updated the midis2jam2 jar file. When I imported a midi file into Terminal, the window opens up showing the instruments not playing the right notes in the beginning when the synthesizer playback actually plays at the very beginning. I meant that the instruments show up at the wrong measure/duration of the midi file when the synthesizer audio playback started at the start of the midi file.

I don't know what caused this bug to happen, but I'm sure that it'll get fixed soon.

**Comment by wyskoj** [comment]
Does it happen every time you open midis2jam2? Have you tried using the [latency fix argument](https://github.com/wyskoj/midis2jam2#using-a-ci-build)? Can you upload a MIDI file that causes this issue?

**Comment by cunningar0807** [comment]
I does happen every time I open a midi file. I'll have to try the latency fix argument. Let me see what I can do.

**Comment by wyskoj** [comment]
Fixed.
