### ISSUE TITLE
Add FluidSynth as a bundled software synth device

### ISSUE THREAD

**Issue by nikitalita** [wyskoj/midis2jam2#25]
**Is your feature request related to a problem? Please describe.**
This would eliminate vastly different sounds and configuration problems on other platforms and enable the use of soundfonts to be easily provided by the user. 

**Describe the solution you'd like**
I had looked around for an ingestible java library for fluidsynth, but I had found none. It appears that FluidSynth got rid of their official JNI implementation a while ago; there's android bindings, but those are specific to the Android platform. 

However, I did find this:
https://github.com/svenmeier/jorgan/tree/master/jorgan-fluidsynth
This implements the relevant classes for `javax.sound.midi`, and it uses a recent version of fluidsynth 2.0. It looks like this could be appropriated. 
I'm not really sure how to build the project, as there are no instructions, but I've left an issue and the author seems decently active.

**Describe alternatives you've considered**
I can't find anything else that is even worth considering; fluidsynth support on java may be slight, but I really can't find any other decent software synth with support for java.

**Comment by wyskoj** [comment]
@nikitalita Did you ever get that fluidsynth library to build and work?

**Comment by nikitalita** [comment]
Yes, I did! I actually managed to get it to build on both Linux and Windows. The windows build takes a fair bit of finangling to get the dependencies behaving, I'll likely write something up about it this weekend.

**Comment by wyskoj** [comment]
Great! I finally got the Java Gervill synth to load an sf2 but I think fluidsynth has more configuration though, so I'm glad you got it to build. Let me know when you get that together, thank you!

**Comment by nikitalita** [comment]
So here's the scoop:
On windows:
Use my fork here: https://github.com/nikitalita/jorgan/tree/fluidsynth-2.2-upgrade

use `choco` to install gcc

in build.properties, set these values to:
```
win.cc = gcc.exe
win.include = <Wherever the include path for the jdk for IDEA is stored>
```
Make sure that the path does NOT include spaces, as Ant is terrible and I hate it and I can't figure out how to get it to accept paths with spaces.

However, I'm not actually certain how to get this to run on windows; while it builds fine on windows, I can't actually get the program to run; it runs ok on Linux.

Regardless, this library seems to work on both Linux and Windows, and you can use it on either. It can be appropriated for use in this.

I'll submit some more issues to help clarify how to get this to run on Windows and how to demonstrate fluidsynth support.

**Comment by nikitalita** [comment]
Alright, I got this to work.

Pull the latest from my branch, build it according to the instructions above, then run it using `run.bat` in the root of the project.

then, open up the fluidsynth disposition at `jorgan-fluidsynth\src\main\dispositions\fluidsynth-example.disposition`

Open up the configuration by clicking the little graph tool in the toolbar, select `fluidsynth sound`, change the audio driver to "wasapi", then change the device to your sound device.

select the keyboard, then change it to the "Real-time sequencer".

Then, CLOSE the edit mode by clicking on the graph tool, then press keys on the keyboard (the middle ones, the ones on the sides aren't configured). You should hear some midi sounds. you can load different sound fonts by editing the fluidsynth sound properties, too.

**Comment by wyskoj** [comment]
Great! I got it to work. I will try and experiment with what's here and see if I can get something built that can just play a MIDI file. Anything else I should know that could help?

**Comment by nikitalita** [comment]
BTW, if you do end up spinning this off, I'd recommend using CMake instead of ant as the build system; this would let you use `vcpkg` for fluidsynth and glib, and you'd have an easier time automatically configuring builds on different platforms. There's a decent example of a JNI-C build with CMake here: https://github.com/remram44/java-cpp-example/blob/master/java-jni/CMakeLists.txt

**Comment by wyskoj** [comment]
midis2jam2 has a MIDI device selector now.
