### ISSUE TITLE
Make the Window Name from the Configurator Window Different from the Name of the 3D Visualization Window

### ISSUE THREAD

**Issue by VGMRUS** [wyskoj/midis2jam2#49]
**Is your feature request related to a problem? Please describe.**

Recently I've discovered your proyect to modernize midijam and I love it since I use the original in my channel VGMRUS in 99% of the videos.

While you version it's amazing I'm actually having some trouble capturing it with OBS with midis2jam2 on window mode since OBS knows what window to capture by the name of the window itself and since both the configurator window and the actual 3D visualization window have the same exact name OBS will a lot of times capture the configurator window instead which is pretty fustrating, and when the 3D windows closes it starts capturing the Config and the next time you open the 3D window again OBS will still record the config and you have to change manually to the 3D window again
![imagen](https://user-images.githubusercontent.com/87239717/125170195-0f2b7f00-e1ae-11eb-989f-84eace6ad9eb.png) 

Here is both the configurator and 3D window seen by OBS, as you can see there's no difference at all which is why OBS does this behavior
![imagen](https://user-images.githubusercontent.com/87239717/125170229-3eda8700-e1ae-11eb-9120-8e7b214c3be8.png)

**Describe the solution you'd like**

Rename the Configurator window from "midis2jam2" to "**midis2jam2 configurator**" or something similar
Or alternatively the 3D window from "midis2jam2" to "**midis2jam2 visualizer**" or something similar

Or both if you want, but by changing one of the two should be enough to make OBS capture reliable

**Comment by wyskoj** [comment]
Changing the window name doesn't resolve the issue because both windows are opened by the same executable. OBS doesn't have a way of differentiating them when the windows change, so unfortunately just renaming them won't fix it. 

Although, I am planning on implementing a built-in recorder sometime in the future which would eliminate the need for OBS.

**Comment by VGMRUS** [comment]
I'm pretty sure it will fix the issue, here are some other programs seen by OBS with the same executable but OBS still sees the different window names:
![imagen](https://user-images.githubusercontent.com/87239717/125200761-92aba580-e26c-11eb-973e-24d64d352b84.png)

In fact capturing by the name (or titles as it calls it) of the window and otherwise the executable itself is the default way OBS records:
![imagen](https://user-images.githubusercontent.com/87239717/125200875-0948a300-e26d-11eb-88f0-7741562970f5.png)

While built-in recording would be nice I would still want to record using OBS because I'm putting an overlay over it, I also even record it portrait mode aka vertical screen/for phones while also recording the audio of Coolsoft VMS going through equalizer APO with a compressor with an virtual audio cable, I can record all that at once with OBS, here are several examples of all of this: https://www.youtube.com/watch?v=2PyXwYV45bo&list=PLuZCrOWyT9ka0IwqXuqSLZnP5AfCoB5Iy

And what if someone wants to make a stream and try to capture midis2jam2 on window mode (a lot of streamers only have 1 monitor and on fullscreen you can't see chat or OBS)? Currently everytime the 3D visualization (aka the window that you want to record) closes OBS starts recording the settings and will keep on capturing it until on OBS you manually change it to the 3D one, so you would basically have to do that once every midi played.

So, please, if it isn't too hard change the title of one of the windows, Thanks.

**Comment by wyskoj** [comment]
Okay, I got it to work, you have to make sure that the window match priority is set to "window title must match" for it to work. Sorry, I initially did some tests renaming the window and had no success, but didn't experiment with the match priority. 

Resolved by 5104deb.
