### ISSUE TITLE
Add auto-cam

### ISSUE THREAD

**Issue by JustaRandomUser12** [wyskoj/midis2jam2#50]
Basically, add an option to automatically randomly choose the multiple different camera angles in order to create an experience more like the original program. Everything else in this program is great, I just wish that automatic camera angles were added.

**Comment by VGMRUS** [comment]
I agree, definitely the feature I miss the most, maybe it could be improved by reacting better to what's happening for example if a new instrument (program change) appears the camera would focus on it or when a instrument stops playing notes it changes quicker to another one, the midi would probably need to be analyzed before playing it live so it knows exactly what instrument is coming so it reacts better

**Comment by wyskoj** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add auto-cam](https://trello.com/c/56Wy2Agq/2-add-auto-cam)

**Comment by wyskoj** [comment]
Autocam is now a feature. Will be included in v.1.5.0.
