### ISSUE TITLE
Add Key/Tempo Change Feature

### ISSUE THREAD

**Issue by VGMRUS** [wyskoj/midis2jam2#51]
**Is your feature request related to a problem? Please describe.**
Since midis2jam2 is a midi player I think adding a key change and tempo change feature like a lot of midi players have on the launcher would be another nice feature that original midijam didn't have

**Describe the solution you'd like**
On the launcher on the settings a key modifier that would normally be on 0 that can be changed from -12 to +12 keys for example
And a Tempo that would normally be at 100% speed that can be changed from 25% to 200% for example 

**Describe alternatives you've considered**
It would be a nice bonus if you could also change these settings while playing a midi on the 3D visualizer window by pressing a button, 4 keyboard buttons 2 for increasing and decreasing key and 2 for tempo speed change, maybe pressing both the increase and decrease buttons would reset it to the default value, text saying current key/tempo might be necessary

**Comment by wyskoj** [comment]
Won't be implemented.
