### ISSUE TITLE
Only the legacy engine prints a stack trace

### ISSUE THREAD

**Issue by iitztoss** [wyskoj/midis2jam2#57]
When a midi file is opened (i used canyon.mid) without using the legacy render, when the application crashes it is impossible to see why. It just simply freezes, without opening a stack trace.
I used the latest build from CI and the problem was a missing texture.
```
Uncaught exception thrown in Thread[jME3 Main,6,main]
AssetNotFoundException: Assets/ChoirPeepVoiceSynth.png (Flipped) (Mipmapped)
```

**Comment by wyskoj** [comment]
Fixed the texture bug. The stack trace can be seen when launching the program from a terminal.
