### ISSUE TITLE
Ideas for rain and applause

### ISSUE THREAD

**Issue by melodicafluff79** [wyskoj/midis2jam2#67]
Rain/Applause Vizualization.  For Rain, i suggest you put a mini diorama and make it play a rain animation. For applause, i suggest you put little hands behind the stage and animate it to look like it's clapping. this program is amazing.

**Comment by MaxGodTier** [comment]
It's not my intention to rain on anyone's parade, but sometimes MIDI instruments don't always reflect their literal names (ie. Synth FX / 102 FX 6 (goblins) [doesn't sound like a goblin at all](https://soundcloud.com/audioalch/goblin-sound-pack-preview)).
[On this website](https://freewavesamples.com/midi-instruments) you can compare how a midi instrument sounds like on different synthesizers and eventually come up with a more reasoned choice than trusting the name alone.

**Comment by wyskoj** [comment]
Applause resolved by 034a765f246258e0243a6970b47b025166885cd7. Closing as this issue pertains to instrument implementation.
