### ISSUE TITLE
Add option for disabling graphics enhancements

### ISSUE THREAD

**Issue by melodicafluff79** [wyskoj/midis2jam2#68]
I've tried running the program on my older computer. but it said something like pixel format not accelerated and illegal monitor state exception current thread not owner? i did a bit of research and it appears that it's something related to my video card being out of date. so i tried updating it but it's all up to date. is that normal?

**Comment by wyskoj** [comment]
I apply some extra fancy graphics options that make it look prettier. I can add an option to disable these, but can't guarantee it'll fix that bug.

**Comment by wyskoj** [comment]
Upstream LWJGL issue.

**Comment by wyskoj** [comment]
Adjusting the samples settings added by f464cd7 may remedy this.
