### ISSUE TITLE
Add special shapes for space lasers

### ISSUE THREAD

**Issue by VGMRUS** [wyskoj/midis2jam2#69]
**Is your feature request related to a problem? Please describe.**

No, it's just a visual idea I had, I don't know if the lasers for the square/saw wave are intentional for these instruments if they are they gave me this idea for the square/saw lead instruments

**Describe the solution you'd like**

Change both the saw wave and square wave lasers to each shoot their visual waves instead of a straight line

Well, you know what they say "a picture is worth a thousand words" so I just photoshopped it:
Here are some square waves examples:

![Full laser Squarer](https://user-images.githubusercontent.com/87239717/141696608-bfd6432f-4519-4243-8e80-94d0ab9626d5.png)

![Full laser](https://user-images.githubusercontent.com/87239717/141696631-fea4265f-d22d-4257-8cbb-6a7f3706d098.png)

![Semi laser](https://user-images.githubusercontent.com/87239717/141696640-eb032b72-7ceb-46c1-ad60-337b939c7deb.png)

and 1 for the saw wave (the wave should be smaller to look better, but you get the point):

![Full laser Saw](https://user-images.githubusercontent.com/87239717/141696669-a744b2f0-f603-483a-b869-92e8163e02d8.png)

**Describe alternatives you've considered**

In case you implement this and If you REALLY want to upgrade this feature then you could make the wave get smaller or bigger depending on the current semitone/pitch, so basically like having a vertical oscilloscope, it definetely would look pretty cool, it would look kinda like (a simpler version of) one of these 3 channels vertically: https://www.youtube.com/watch?v=pgPEaI0GHBI

**Comment by wyskoj** [comment]
Not a bad idea! I'll experiment with this.

**Comment by s11141827** [comment]
Actually the Keyboards look a bit simpler

**Comment by s11141827** [comment]
I think adding the Keyboards that control the Lasers would be super cool, the worlds coolest dual Instrument

**Comment by s11141827** [comment]
I think displaying the Synth Square Wave & Synth Sawtooth Wave as both Shooting Lasers & Keyboards working together would be the coolest enhancement of all so you can see the instrument from even more angles.

**Comment by s11141827** [comment]
I'm excited to see this in the next update. In the meanwhile maybe a Test version could help me get started.

**Comment by wyskoj** [comment]
I think in the interest of keeping the current style (I haven't touched the space lasers in over two years now), I am hesitant to change their appearance. I suspect this might not be well received by the community.
