### ISSUE TITLE
Add support for lyrics events

### ISSUE THREAD

**Issue by AndroYD84** [wyskoj/midis2jam2#70]
**Is your feature request related to a problem? Please describe.**

Not a problem, just a missing feature that would be cool to have.

**Describe the solution you'd like**

When a MIDI file contain lyrics, show them on screen as subtitles and highlight the text that's being played, just like a karaoke session.

**Describe alternatives you've considered**

It could be speech bubbles or colored text coming from a singer cutout (as the chorus), MIDI 1 format may contain multiple lyrics tracks (ie SATB or barbershop quartet), so arrangement on screen must be chosen carefully.

**Additional context**
Here's some example [MIDI 0](https://github.com/AndroYD84/Files/raw/master/karexample/grandfatherclock_midi0.mid) and [MIDI 1](https://github.com/AndroYD84/Files/raw/master/karexample/billsbillsbills_midi1.mid) file containing lyrics events and a [demo video](https://s1.webmshare.com/q11Y0.webm).

**Comment by wyskoj** [comment]
Simple lyrics events are now implemented. Will be included in v.1.5.0.
