### ISSUE TITLE
Concept Art for Bird Tweet

### ISSUE THREAD

**Issue by TheCococQuartz** [wyskoj/midis2jam2#75]
**The Feature**
Yo I just had the sickest idea for the Bird Tweet, but because I can't 3D model or code, I've decided to illustrate my idea instead.

**The Model**
![IdeaForBird](https://user-images.githubusercontent.com/96637234/147374418-6e0966ee-f5e0-45ba-a3ed-b712fddb824f.png)
Explains itself really.
It works like the Choir except with Birds.
It's positioned right of where the Choir is.

**Animation**
Instead of doing the basic Choir/Brass animation, I think the model should ascend on the attack, descend on the decay, and the mouth should close when the note is released to better match the sound it produces, [like this](https://user-images.githubusercontent.com/96637234/147374421-9a722f4c-ea19-4a2a-bc7d-6877f8ce5ed9.mp4). (note: C5 is Middle C)
Since the attack would increases and decreases as you go up and down in pitch, I have 2 suggestions on how you can account for this. (Assuming I understand how coding works)

Idea 1: Real-Time Calculations
Since the Bird Tweet uses one soundbite, (making said soundbite faster or slower depending on pitch), you could, for example, have 1 note like C5 have a set attack time, then use a formula to determined how much the attack should be changed based on how far away any given note is from the one.
For what that formula would be, i dunno ¯\_(ツ)_/¯

Idea 2: _The List_
Perhaps instead you can have a document that has already done the math for attack times ranging from F2 - C7 (anything below F2 stops going down in pitch and anything above C7 would be so fast you might as well just do the normal Choir/Brass animation).
So if something like E3 is played it can just pull the attack time for E3 from _the list_ instead of doing the math itself.

**Alternatives**
Since you can choose from a wide variety of bird species to use for the model, feel free to can change the colors on this to be whatever bird or original design you may have in mind (y'know assuming you decide to use this design for the 3D model).

**Comment by wyskoj** [comment]
Wow, this is all great! Thank you for the ideas, definitely going to implement this.

**Comment by wyskoj** [comment]
The prototype is done.

**Comment by lickington** [comment]
Cool!
