### ISSUE TITLE
Add Support for Bass Guitar Notes

### ISSUE THREAD

**Issue by TheCococQuartz** [wyskoj/midis2jam2#76]
**Is your feature request related to a problem? Please describe.**
Its not a big problem, but I've written a song recently that had a guitar playing many notes that are out of range, since there are bass guitars that can play notes lower that what this program can visualize, I believe that these notes should be accounted for.

**Describe the solution you'd like**
If any guitar instruments are identified in any channel (MIDI patches 25-32 and 34-40), there should be an option in the GUI to change any of those channels to bass tuning (ie. change the Slap Bass 2 in channel 4 to bass tuning). This would be shown by having the strings on said guitar be more thicker.

**Describe alternatives you've considered**
You could also not do this, I guess.

**Comment by wyskoj** [comment]
Guitar and BassGuitar will automatically use a drop D tuning if there is any note below the instrument's lowest E. This is shown by that tuning peg being rotated.
