### ISSUE TITLE
JavaFX is not packaged properly

### ISSUE THREAD

**Issue by wyskoj** [wyskoj/midis2jam2#78]
![image](https://user-images.githubusercontent.com/31376393/149628771-cfe21aff-3020-4878-83d2-6623aa7f090a.png)

**Comment by wyskoj** [comment]
I'm assuming this is a JavaFX packaging issue.

**Comment by s11141827** [comment]
I have this same error on Windows

**Comment by s11141827** [comment]
Every time it finishes loading, it like UN-installs itself, can you PLZ fix it?

**Comment by wyskoj** [comment]
I forgot to enable a setting in the install4j that adds JavaFX, this should fix it. I will close once I confirm this.

**Comment by s11141827** [comment]
Good news mine works & it's running smoothly

**Comment by s11141827** [comment]
Thank you, now I can use Midis2jam2. The next idea is to have the Syn
Sawtooth Lead & Syn Square Lead displayed as Keyboards controlling their
corresponding lasers cause it'll allow people to see the instrument from
more angles.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by s11141827** [comment]
Make sure you keep JavaFX on & also keep me informed about the next update

**Comment by s11141827** [comment]
Let me know when confirmed

**Comment by wyskoj** [comment]
This is giving me too many issues so I'm reverting back to JFileChooser cause I can 99.9% guarantee it will work.
