### ISSUE TITLE
Fix this Error of me downloading

### ISSUE THREAD

**Issue by s11141827** [wyskoj/midis2jam2#79]
I'm trying to download this new version of MIDIs2jam2 but it errors & uninstalls itself, PLZ fix it.

**Comment by wyskoj** [comment]
What's the error?

**Comment by s11141827** [comment]
I think I need to restart my computer so that it goes on smoothly

**Comment by s11141827** [comment]
I've been trying to install this App but it closes & then the file goes missing

**Comment by s11141827** [comment]
I try to download it on my Dell Computer but it doesn't seem to work
properly as it should
