### ISSUE TITLE
Tracks with multiple instruments don't work properly

### ISSUE THREAD

**Issue by TheCococQuartz** [wyskoj/midis2jam2#81]
**Describe the bug**
When a track switches instruments the first note that new instrument plays doesn't get visualized.

**Offending MIDI file**
This one: [WhyCantIUploadMidiFiles.zip](https://github.com/wyskoj/midis2jam2/files/7876077/WhyCantIUploadMidiFiles.zip)
Pay attention to the Oboe, Vibraphone, Fiddle, and Pizzicato, all of those instruments are on one track.
This can be most obviously seen at the start of the Fiddle solo before the loop.

**System**
Still Windows 10 btw

**Comment by wyskoj** [comment]
Yep, it took me a minute but I see it now. I'll look into this!
