### ISSUE TITLE
Reset MIDI controllers when using external device

### ISSUE THREAD

**Issue by VGMRUS** [wyskoj/midis2jam2#87]
**Describe the bug**
I've noticed that when using Coolsoft Virtual Midi Synth as output the midi values don't get reset when opening a midi (you have to close midis2jam2 completely and reopen it to reset it to stock), it just goes with whatever the last midi value update there was even when using different midis. For example if I play 1.mid and this midi has fine tuning on channel 1 to +50 cents (done by CC100 at 1 and CC101 at 0 then CC6 to fine tune 64 being 0cents from normal) then I close it and then play 2.mid which doesn't have fine tuning then because values weren't reset when opening this 2.mid it still has the +50 cents on channel 1 set making it completely unintented

**Offending MIDI file**
Upload the MIDI file that causes the bug here.
Sure, the example from before it's based of exactly that happening to me so here, just play 1.mid and then 2.mid you will notice 2.mid instruments will be detuned because of the 1.mid tuning. if you then close midis2jam2 and open 2 only the instruments will sound as they should
[Midis.zip](https://github.com/wyskoj/midis2jam2/files/7893001/Midis.zip)

**Expected behavior**
When pressing the start button ALL the midi data/cc that were previously send should get reset into the default state

**Comment by wyskoj** [comment]
Try out this build that should reset the MIDI device when another song starts and let me know if this seems to resolve it:
https://ci.appveyor.com/project/wyskoj/midis2jam2/builds/43034014/artifacts

**Comment by VGMRUS** [comment]
Yes, it did fix it, everything plays as it should now since the midi does get reset to default, Thanks

**Comment by wyskoj** [comment]
Sweet!
